Repository Komet/MediaElch, pull requests merged in 2018-05, with the labels that each got.

#413 Fix dependencies to build and install on Ubuntu 18.04, while maintain…
  debian/control
Labels: installation

#398 Add changelog
  changelog.md
Labels: documentation

#416 [Stylesheet] Fix css loading
  main.cpp
Labels: bug, high priority

#417 [TravisCI] Fix version regex in package script
  travis-ci/package.sh
Labels: bug

#418 [TravisCI] Update deployment
  .gitignore
  .travis.yml
  travis-ci/configure.sh
  travis-ci/install_dependencies.sh
  travis-ci/macOS/backgroundImage.tiff
  travis-ci/package.sh
  travis-ci/utils.sh
  travis-ci/win/dll_list.txt
Labels: in-progress

#458 [NFO] Fix thumb in episode if writeThumbUrlsToNfo is false
  mediaCenterPlugins/XbmcXml.cpp
Labels: bug
